# Generated by Django 5.2.4 on 2025-07-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('music_producer', 'music producer'), ('game_developer', 'game developer'), ('it', 'IT')], default='admin', max_length=20),
        ),
    ]
