# Generated by Django 5.2.4 on 2025-07-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_user_task_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('active', 'فعال'), ('archived', 'آرشیو شده')], default='pending', max_length=10),
        ),
    ]
