# Generated by Django 5.2.4 on 2025-07-10 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='description',
            field=models.TextField(blank=True, help_text='توضیح مختصر درباره کارهای انجام شده (اختیاری)'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='tasks.project'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='weekly_reports/'),
        ),
    ]
